name: CI

on:
  push:
    branches:
      - master

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        env:
          TOKEN: ${{ secrets.TOKEN }}
          GITHUB_USER: sgama
          GITHUB_IMAGE_NAME: vnc
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_KEY: ${{ secrets.DOCKERHUB_KEY }}
          DOCKERHUB_IMAGE_NAME: kali-linux
        run: |
          echo 'CI Job Start'
          echo 'DockerHub Registry Login'
          docker login -u $DOCKERHUB_USER --password-stdin <<< "${{ secrets.DOCKERHUB_KEY }}"
          echo 'Github Package Registry Login'
          docker login docker.pkg.github.com -u $GITHUB_USER --password-stdin <<< "${{ secrets.TOKEN }}"
          echo 'Docker Build...'
          docker build . --tag $DOCKERHUB_USER/$DOCKERHUB_IMAGE_NAME:latest
          docker tag $DOCKERHUB_USER/$DOCKERHUB_IMAGE_NAME:latest docker.pkg.github.com/$GITHUB_REPOSITORY/$GITHUB_IMAGE_NAME:latest
          echo 'Pushing Image to Dockerhub ...'
          docker push $DOCKERHUB_USER/$DOCKERHUB_IMAGE_NAME:latest
          echo 'Pushing Image to Github ...'
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/$GITHUB_IMAGE_NAME:latest
          echo 'CI Job Complete'